//------------------------------------------------------------------------------
// GÉNÉRÉ — NE PAS ÉDITER À LA MAIN.
// Source : schema/state-bus.v1.schema.json
// Regénération : dotnet run --project schema/generator
//------------------------------------------------------------------------------
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace Overkit.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Premier message de la Sonde à chaque connexion (EXG-004). Le host refuse ou dégrade selon compatibilité.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class HandshakeMessage
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public object Type { get; set; } = default!;

        /// <summary>
        /// SemVer de la Sonde
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("probe_version")]
        public string Probe_version { get; set; } = default!;

        /// <summary>
        /// Version du présent schéma implémentée par la Sonde
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("schema_version")]
        public string Schema_version { get; set; } = default!;

        /// <summary>
        /// Build du jeu détecté, 'unknown' si indisponible
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("game_build")]
        public string Game_build { get; set; } = default!;

        /// <summary>
        /// Version du mapping.json chargé, 'none' si intégré en dur
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mapping_version")]
        public string Mapping_version { get; set; } = default!;

    }

    /// <summary>
    /// Snapshot partiel ou complet de l'état du jeu. Tout domaine absent est réputé inchangé depuis le dernier message ; tout domaine présent remplace intégralement sa version précédente.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StateMessage
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public object Type { get; set; } = default!;

        /// <summary>
        /// Horloge monotone de la Sonde en millisecondes (pas une heure calendaire)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("t_ms")]
        public int T_ms { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("player")]
        public Player? Player { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("world")]
        public World? World { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("inventory")]
        public Inventory? Inventory { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("palbox")]
        public Palbox? Palbox { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("party")]
        public Party? Party { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("bases")]
        public Bases? Bases { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nearby")]
        public Nearby? Nearby { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("collectors")]
        public Collectors? Collectors { get; set; } = default!;

    }

    /// <summary>
    /// ok = donnée fraîche et fiable ; degraded = donnée présente mais partielle ou datée (collecteur ralenti) ; unavailable = chemin de réflexion non résolu ou domaine hors de portée (EXG-003).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum FieldStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ok")]
        Ok = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"degraded")]
        Degraded = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"unavailable")]
        Unavailable = 2,


    }

    /// <summary>
    /// Coordonnées monde Unreal (cm). La transformation vers les coordonnées carte relève du dataset (map_calibration), pas du State Bus.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Vector3
    {

        [System.Text.Json.Serialization.JsonPropertyName("x")]
        public double X { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("y")]
        public double Y { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("z")]
        public double Z { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Gauge
    {

        [System.Text.Json.Serialization.JsonPropertyName("current")]
        public double Current { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("max")]
        public double Max { get; set; } = default!;

    }

    /// <summary>
    /// Cadence cible : position/rotation 10 Hz ; niveau/HP/stamina event-driven + resync. Mapping validé : PalPlayerCharacter.RootComponent.RelativeLocation. Niveau/HP : mapping à découvrir (piste : PalPlayerState).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Player
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("position")]
        public Vector3? Position { get; set; } = default!;

        /// <summary>
        /// Cap en degrés, utile pour la flèche de routing
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("rotation_yaw")]
        public double? Rotation_yaw { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("level")]
        public int? Level { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("hp")]
        public Gauge? Hp { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("stamina")]
        public Gauge? Stamina { get; set; } = default!;

    }

    /// <summary>
    /// Cadence cible : 1 Hz.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class World
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("time")]
        public WorldTime? Time { get; set; } = default!;

        /// <summary>
        /// Identifiant brut du jeu, non traduit — mapping à découvrir
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("weather")]
        public string? Weather { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("world_name")]
        public string? World_name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("is_multiplayer")]
        public bool? Is_multiplayer { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class WorldTime
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        /// <summary>
        /// GameDateTime.Ticks, unités de 100 ns (mapping validé : PalGameStateInGame.WorldTime)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("ticks")]
        public int? Ticks { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("day")]
        public int? Day { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("hour")]
        public int? Hour { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("minute")]
        public int? Minute { get; set; } = default!;

        /// <summary>
        /// Piste : délégués OnNightStart/OnNightEnd de PalTimeManager, sinon dérivé des heures
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("is_night")]
        public bool? Is_night { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ItemStack
    {

        /// <summary>
        /// Identifiant statique du jeu ; le libellé/l'icône viennent du dataset (refdata)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("item_id")]
        public string Item_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("count")]
        public int Count { get; set; } = default!;

    }

    /// <summary>
    /// Items joueur + coffres de la base active (§3.1). Event-driven + resync 30 s. Mapping à découvrir.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Inventory
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("containers")]
        public System.Collections.Generic.ICollection<InventoryContainer>? Containers { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class InventoryContainer
    {

        [System.Text.Json.Serialization.JsonPropertyName("container_id")]
        public string Container_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("kind")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<InventoryContainerKind>))]
        public InventoryContainerKind Kind { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("slots")]
        public System.Collections.Generic.ICollection<ItemStack> Slots { get; set; } = new System.Collections.ObjectModel.Collection<ItemStack>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Pal
    {

        /// <summary>
        /// Identifiant stable de l'individu (pour suivre un Pal entre snapshots)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("instance_id")]
        public string Instance_id { get; set; } = default!;

        /// <summary>
        /// Clé vers refdata (pals.json du dataset)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("species_id")]
        public string Species_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("nickname")]
        public string? Nickname { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("gender")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<PalGender>))]
        public PalGender? Gender { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("level")]
        public int? Level { get; set; } = default!;

        /// <summary>
        /// Identifiants bruts, libellés via refdata
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("passives")]
        public System.Collections.Generic.ICollection<string>? Passives { get; set; } = default!;

        /// <summary>
        /// IVs 0-100 (donnée non visible en jeu — assumé et documenté, cf. R6)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("talents")]
        public Talents? Talents { get; set; } = default!;

        /// <summary>
        /// Aptitude → rang (ex. kindling: 2)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("work_suitabilities")]
        public System.Collections.Generic.IDictionary<string, int>? Work_suitabilities { get; set; } = default!;

    }

    /// <summary>
    /// Tous les Pals possédés (§3.1). Event-driven + resync 30 s. Mapping à découvrir — domaine le plus riche, socle des modules Accouplement inversé et Audit de base.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Palbox
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("pals")]
        public System.Collections.Generic.ICollection<Pal>? Pals { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Party
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("member_instance_ids")]
        public System.Collections.Generic.ICollection<string>? Member_instance_ids { get; set; } = default!;

    }

    /// <summary>
    /// Pals assignés et jauges par base (§3.1). Socle du module Audit de base. Mapping à découvrir.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Bases
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("list")]
        public System.Collections.Generic.ICollection<BaseInfo>? List { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BaseInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("base_id")]
        public string Base_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("position")]
        public Vector3? Position { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("workers")]
        public System.Collections.Generic.ICollection<BaseWorker>? Workers { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BaseWorker
    {

        [System.Text.Json.Serialization.JsonPropertyName("instance_id")]
        public string Instance_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("hunger")]
        public Gauge? Hunger { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("sanity")]
        public Gauge? Sanity { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("is_working")]
        public bool? Is_working { get; set; } = default!;

    }

    /// <summary>
    /// Pals dans le rayon de streaming (§3.1), cadence 2 Hz. Socle des modules Routing de farm et Capture assist.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Nearby
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FieldStatus>))]
        public FieldStatus Status { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("actors")]
        public System.Collections.Generic.ICollection<NearbyActor>? Actors { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class NearbyActor
    {

        [System.Text.Json.Serialization.JsonPropertyName("species_id")]
        public string Species_id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("level")]
        public int? Level { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("hp")]
        public Gauge? Hp { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("position")]
        public Vector3? Position { get; set; } = default!;

        /// <summary>
        /// Distance au joueur en cm
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("distance")]
        public double? Distance { get; set; } = default!;

    }

    /// <summary>
    /// Statut de chaque collecteur de la Sonde, clé = nom du collecteur (ex. player_position, world_time, palbox). Publié à chaque changement.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Collectors : System.Collections.Generic.Dictionary<string, FieldStatus>
    {

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum InventoryContainerKind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"player")]
        Player = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"key_items")]
        Key_items = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"chest")]
        Chest = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"food_box")]
        Food_box = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"other")]
        Other = 4,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum PalGender
    {

        [System.Runtime.Serialization.EnumMember(Value = @"male")]
        Male = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"female")]
        Female = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"unknown")]
        Unknown = 2,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Talents
    {

        [System.Text.Json.Serialization.JsonPropertyName("hp")]
        public int? Hp { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("attack")]
        public int? Attack { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("defense")]
        public int? Defense { get; set; } = default!;

    }
}